// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwsbkmswwqnvglhxrwoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3c2JrbXN3d3FudmdsaHhyd29hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4Mjk1NDEsImV4cCI6MjA3NDQwNTU0MX0.HnzFYDkBXm4bp6ag8jjxRfNKX9NDBKf6otBaz232ZRc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});